[tool.poetry]
name = "ultimate-pollbot"
version = "1.0.0"
description = "A telegram bot for creating all kinds of polls."
authors = ["Arne Beer <contact@arne.beer>"]
license = "MIT"
repository = "https://github.com/nukesor/poll-bot"

[tool.poetry.dependencies]
python = ">=3.6"
raven = "6.10"
alembic = "1.0"
python-telegram-bot = "^12.0.0b1"
SQLAlchemy = "^1.2"
sqlalchemy-utils = "^0.33"
psycopg2-binary = "^2.8"
python-dateutil = "^2.8"
toml = "^0.10"
python-i18n = {version = "^0.3.6", extras = ["yaml"]}
flask = "^1.1"
flask_restful = "^0.3.7"

matplotlib = "3.0"
pandas = "^0.24"
pillow = "^6.0"

[tool.poetry.dev-dependencies]
pytest-mock = "^1.10"
pytest = "^4.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
